### ISSUE TITLE
Bad *.csv error protection

### ISSUE THREAD

**Issue by pieslinger** [dirkjanfaber/node-red-contrib-victron-modbus#2]
I mixed up the csv file that I scp'd into my node-red directory. As soon as I would drop the node onto the palette, Node Red would crash with this error:
```
26 Nov 20:14:46 - [red] Uncaught Exception:
26 Nov 20:14:46 - [error] Error: Invalid Opening Quote: a quote is found on field 0 at line 1, value is "{"
    at Object.parse (/usr/src/node-red/node_modules/csv-parse/dist/cjs/index.cjs:791:21)
    at Parser._transform (/usr/src/node-red/node_modules/csv-parse/dist/cjs/index.cjs:1331:26)
    at Parser.Transform._read (internal/streams/transform.js:205:10)
    at Parser.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Parser.Writable.write (internal/streams/writable.js:303:10)
    at ReadStream.ondata (internal/streams/readable.js:731:22)
    at ReadStream.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
```

I am just bringing it to your attention in case some error handling could be built in here rather than crashing Node Red. I will not make the same mistake!

**Comment by dirkjanfaber** [comment]
Thanks. Added extra checking, even if it would only happen for very few users.
